### ISSUE TITLE
Trouble getting passed DOS blocks and finding peers

### ISSUE THREAD

**Issue by zmitton** [etclabscore/multi-geth-fork#11]
I believed my DB might have been corupted. So i 
- deleted Library Ethereum/ethereumClassic files
- did a brew uninstall ethereum
- pulled from etcLabsCore/multigeth/master
- ran acchive node freom scratch on mac with the following command

```
multigeth  --classic --syncmode full --bootnodesv4 enode://158ac5a4817265d0d8b977660b3dbe9abee5694ed212f7091cbf784ddf47623ed015e1cb54594d10c1c46118747ddabe86ebf569cf24ae91f2daa0f1adaae390@159.203.56.33:30303 --rpccorsdomain '*' --gcmode archive --rpc  --cache 2048 --nat extip:127.0.0.1
```

I got to about ~block 2.5Million. started seeing errors like this and i could not get past them:

https://gist.github.com/zmitton/fa32083de52ca430cecd804e8e0df12b

a few days later i
- deleted Library Ethereum/ethereumClassic files again
- did a make geth
- make all

restarted the chain, and spent at least a day with no peers. Here is what that looked like on `--verbosity 5`:

https://gist.github.com/zmitton/e3c0e41afacf4cf4162fc2e2ef031960

Finally it just found a single peer and started to download. However I only have _one_. Was hoping there was a way to get a lot more than one.

**Comment by meowsbits** [comment]
> pulled from etcLabsCore/multigeth/master

One thing is you should pull from https://github.com/ethoxy/multi-geth; that's where the edge is. etclabscore is not guaranteed to be up to date, it's just a developers-only working version.


Your [last log file gist ](https://gist.github.com/zmitton/e3c0e41afacf4cf4162fc2e2ef031960) shows logs from about 30 seconds worth of running, and it appears to have gone from startup to sync in that time. :confused: 

I'm looking closer at your first report now, and will get back to you

**Comment by meowsbits** [comment]
I just hit 4M overnight on `--syncmode full --gcmode archive`. Built from `7b0a0b3b902c12452c690b9775ded60b37e49e90`. :confused: 

But on Linux. Going to pick up my freshly repaired Mac today and will be able to try another round of repro.

**Comment by meowsbits** [comment]
Given ![took 3 days :open_mouth:](https://cdn.discordapp.com/attachments/543112485558026240/560783063802707978/unknown.png) - is this resolved? @zmitton

**Comment by meowsbits** [comment]
talked in person, afaiu is resolved. :heavy_check_mark:
