### ISSUE TITLE
travis release deploy key

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/multi-geth-fork#26]
travis ci build failing at release stage: https://travis-ci.org/etclabscore/multi-geth/jobs/565021892#L644

in order to get [travis release artifacts deploying](https://docs.travis-ci.com/user/deployment/releases/), we need to fix this line https://github.com/etclabscore/multi-geth/blob/master/.travis.yml#L17

rel #25 

imo the best way to do this is to set up an oauth key for etclabscore/ and use that so that the key is not tied to any personal account. @chunfuyang, I cannot view etclabscore/ admin settings -- can you make and privately share one of these to me so I can continue with this?

**Comment by meowsbits** [comment]
cc @r8d8

**Comment by tzdybal** [comment]
I prepared working solution for this for 1.9.2 release. We can use the config from release branch.

**Comment by tzdybal** [comment]
See: https://travis-ci.org/etclabscore/multi-geth/jobs/565221252#L647

**Comment by meowsbits** [comment]
And @tzdybal this deploy corresponds to [this release](https://github.com/etclabscore/multi-geth/releases/tag/v1.9.2)?

**Comment by tzdybal** [comment]
@meowsbits yes

**Comment by meowsbits** [comment]
Cool - so should we merge https://github.com/etclabscore/multi-geth/compare/master...etclabscore:release/1.9.2 into master ?
