### ISSUE TITLE
Get multi geth implementing open-rpc 

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/multi-geth-fork#3]
> maybe first cut just returns our spec?
@shanejonas 

Copied from https://github.com/etclabscore/ethereum.go-ethereum/issues/2

**Comment by shanejonas** [comment]
![MultGethRpc](https://user-images.githubusercontent.com/364566/54172981-4605f480-443d-11e9-9e29-80c580f9edae.png)


I broke this down a bit to hopefully show the **vision** for multi geth rpc

**Comment by meowsbits** [comment]
Rel #4

**Comment by BelfordZ** [comment]
![image](https://user-images.githubusercontent.com/1787231/55949853-65dd3380-5c08-11e9-8d09-169f1366f287.png)

**Comment by BelfordZ** [comment]
Man... those array indexes as error messages are painful!
