### ISSUE TITLE
discuss whether eip1108 implementation should depend on eip213

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/multi-geth-fork#62]
https://eips.ethereum.org/EIPS/eip-1108

https://github.com/etclabscore/multi-geth/blob/up/multi-geth/core/vm/contracts.go#L61-L68

rel #54

**Comment by tzdybal** [comment]
You can't reduce cost of a precompiled contract (EIP-1108) if it's not defined (EIP-213). Or I'm missing something?

**Comment by meowsbits** [comment]
Yep. Agreed.
